fake_postman/src/Entity/ReqUser.php
<?php

namespace App\Entity;

use App\Repository\ReqUserRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReqUserRepository::class)
 */
class ReqUser
{
    const METHOD = [
        0 => 'GET',
        1 => 'POST',
        2 => 'UPDATE',
        3 => 'DELETE'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Method;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Token;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Body;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reqUsers")
     */
    private $UserReq;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reqResponse;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMethod(): ?string
    {
        return $this->Method;
    }

    public function setMethod(string $Method): self
    {
        $this->Method = $Method;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->Url;
    }

    public function setUrl(string $Url): self
    {
        $this->Url = $Url;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->Token;
    }

    public function setToken(?string $Token): self
    {
        $this->Token = $Token;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->Body;
    }

    public function setBody(?string $Body): self
    {
        $this->Body = $Body;

        return $this;
    }

    public function getUserReq(): ?User
    {
        return $this->UserReq;
    }

    public function setUserReq(?User $UserReq): self
    {
        $this->UserReq = $UserReq;

        return $this;
    }

    public function getReqResponse(): ?string
    {
        return $this->reqResponse;
    }

    public function setReqResponse(?string $reqResponse): self
    {
        $this->reqResponse = $reqResponse;

        return $this;
    }
}

fake_postman/src/Controller/RequestIndexController.php
<?php

namespace App\Controller;

use App\Entity\ReqUser;
use App\Form\ReqUserType;
use App\Repository\ReqUserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Security\Core\Security;

class RequestIndexController extends AbstractController
{
    /**
     * @var ReqUserRepository
     */

    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;
    /**
     * @var Security
     */
    private $security;

    public function __construct(ReqUserRepository $repository, EntityManagerInterface $em, Security $security)
    {
        $this->repository = $repository;
        $this->em = $em;
        $this->security = $security;
    }

    /**
     * @Route("/request/index", name="request_index")
     * @param Request $request
     * @param $repository
     * @return Response
     */
    public function index(Request $request,ReqUserRepository $repository) : Response
    {
        $req = new ReqUser();
        $form = $this->createForm(ReqUserType::class, $req);
        $form->handleRequest($request);
        $client = HttpClient::create();
        $user = $this->security->getUser();
        $requs = $this->repository->findBy(['UserReq' => $user]);

        dump($requs);

        if ($form->isSubmitted() && $form->isValid()){
            $meth = $form->get('Method')->getData();
            $url = $form->get('Url')->getData();
            $token = $form->get('Token')->getData();
            $body = $form->get('Body')->getData();

            if ($meth == 0){
                $methode = "GET";
                $response = $client->request($methode, $url, [
                    'headers' => [
                        'token' => $token,
                    ],
                ]);
                $content = $response->getContent();
                var_dump($content);
            } elseif ($meth == 1) {
                $methode = "POST";
                $response = $client->request($methode, $url, [
                    'headers' => [
                        'token' => $token,
                    ],
                    'body' => [
                        $body
                    ]
                ]);
                $content = $response->getContent();
                var_dump($content);
            } elseif ($meth == 2) {
                $methode = "UPDATE";
                $response = $client->request($methode, $url, [
                    'headers' => [
                        'token' => $token,
                    ],
                    'body' => [
                        $body
                    ]
                ]);
                $content = $response->getContent();
                var_dump($content);
            } elseif ($meth == 3) {
                $methode = "DELETE";
                $response = $client->request($methode, $url, [
                    'headers' => [
                        'token' => $token,
                    ],
                    'body' => [
                        $body
                    ]
                ]);
                $content = $response->getContent();
                var_dump($content);
            }



            $data = new ReqUser();
            $data->setMethod($meth)
            ->setUrl($url)
            ->setToken($token)
            ->setBody($body)
            ->setReqResponse($content)
            ->setUserReq($user);
            $this->em->persist($data);
            $this->em->flush();
            return $this->redirectToRoute('request_index');
        }

        return $this->render('request_index/index.html.twig', [
            'request' => $req,
            'form' => $form->createView(),
            'controller_name' => 'RequestIndexController',
            'requs' => $requs
        ]);
    }
}

fake_postman/templates/request_index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RequestIndexController!{% endblock %}

{% block body %}
    <div class="jumbotron text-center">
        <div class="container">
            <h1>Nouvelle requête</h1>
            <a href={{ path('app_logout') }}>
                Se déconnecter
            </a>
        </div>
    </div>
    <div class="row flex">
        <div style="margin-left:auto; margin-right: auto">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            </br>
            <button class="btn btn-lg btn-primary" type="submit">
                Envoyer
            </button>


            {{ form_end(form) }}
        </div>
    </div>

    <div class="jumbotron text-center">
        <div class="container">
            <h1>Toutes vos requêtes</h1>
        </div>
    </div>

    <div class="row flex">
        {% for requ in requs %}
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {% if requ.method == 0 %}
                                <h1>GET</h1>
                            {% endif %}
                            {% if requ.method == 1 %}
                                <h1>POST</h1>
                            {% endif %}
                            {% if requ.method == 2 %}
                                <h1>UPDATE</h1>
                            {% endif %}
                            {% if requ.method == 3 %}
                                <h1>DELETE</h1>
                            {% endif %}

                        </h5>
                        <p class="card-text">URL : {{ requ.url }}</p>
                        <p class="card-text">token : {{ requ.token }}</p>
                        <p class="card-text">Réponse : {{ requ.reqresponse }}</p>
                    </div>
                </div>
            </div>


        {% endfor %}
    </div>

{% endblock %}